# Generated by Django 5.2.3 on 2025-07-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameApplication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
